### PR TITLE
Added code for buttons

### PR DESCRIPTION
**Pull request by juanshishido**
Added Travis and Coveralls buttons.

### CODE REVIEW

**Comment by juanshishido** [comment]
@berithsu, @wtsanderson, @jonmigueljara, and @yuanyiwu can someone please review and make comments? Once it's reviewed, *someone else* should accept the PR. Thanks!

**Comment by wtsanderson** [comment]
Looks real good. I'll merge with master.

**Comment by juanshishido** [comment]
@wtsanderson: thanks for reviewing, but I still need someone to merge. @berithsu, @jonmigueljara, @yuanyiwu: could any of you please merge?

**Comment by wtsanderson** [comment]
Oh I get it now. My bad.

**Comment by juanshishido** [comment]
Thanks, @jonmigueljara and @wtsanderson!

**Pull request merged**
